### ISSUE TITLE
Unable to integrate project

### ISSUE THREAD

**Issue by martintschemernjak** [NativeScript/nativescript-remote-builds#14]
Hi,

I followed the tutorial but i can not get it to work...
I'm on a windows machine and i try to build a nativescript app for ios.

This is how my .nsremote.config.json looks like:

`{
    "circleci": {
        "sshRepositoryURL": "git@github.com:**********************************.git"
    }
}`

my .nsremote.env.json:

`{
    "local": {
        "CIRCLE_CI_API_ACCESS_TOKEN": "**********************************"
    }
}`

I followed the setup for CircleCI, created an account there, linked it to my Github account and uploaded a ssh key. The same ssh key i have localy.

If I try to build the app with tns build ios, I get the following message:

> Unable to integrate the "*************************" project with Circle CI. Make sure that "************************" is an initialized GitHub repository and the Circle CI OAuth application is authorized in your GitHub organization - https://circleci.com/integrations/github

If I take a look into CircleCI I see that the build failed, but the error message there is the following:

> #!/bin/sh -eo pipefail
> # No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
> # 
> # -------
> # Warning: This configuration was auto-generated to show you the message above.
> # Don't rerun this job. Rerunning will have no effect.
> false
> 

If I now create a .circleci/config.yml file like this:
```
version: 2
jobs:
   build:
     docker:
       - image: node:13
     steps:
       - checkout

       - restore_cache:
           keys:
           - v1-dependencies-{{ checksum "package.json" }}
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-

       - run: npm install

       - save_cache:
           paths:
             - node_modules
           key: v1-dependencies-{{ checksum "package.json" }}
```
the build runs through on CircleCI, but I still get the error message "Unable to integrate the project" like above.

So my questions are now:
* Does anybody have an idea, what the "Unable to integrate the project" error means? As I said I am connected with github to my circleCI Account
* Do I need a .circleci/config.yml file? It is not mentioned in the tutorials.
* If I need the .circleci/config.yml file, how does it have to look like to build an app for ios?

Thank you very much, 
Best regards,
Martin
